/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "echo.h"

bool_t
xdr_hello (XDR *xdrs, hello *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->text, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hello_echo (XDR *xdrs, hello_echo *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->text_echo, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
