/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ECHO_H_RPCGEN
#define _ECHO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct hello {
	char text[256];
};
typedef struct hello hello;

struct hello_echo {
	char text_echo[256];
};
typedef struct hello_echo hello_echo;

#define ECHO_PROG 0x31230000
#define ECHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ECHOPROC 1
extern  hello_echo * echoproc_1(hello *, CLIENT *);
extern  hello_echo * echoproc_1_svc(hello *, struct svc_req *);
extern int echo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ECHOPROC 1
extern  hello_echo * echoproc_1();
extern  hello_echo * echoproc_1_svc();
extern int echo_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_hello (XDR *, hello*);
extern  bool_t xdr_hello_echo (XDR *, hello_echo*);

#else /* K&R C */
extern bool_t xdr_hello ();
extern bool_t xdr_hello_echo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ECHO_H_RPCGEN */
